### ISSUE TITLE
Keys as atoms

### ISSUE THREAD

**Issue by tsloughter** [soranoba/mustache#2]
Rebar and relx templates use atoms as keys. Could mustache convert the data key to an atom if the value isn't found for the string, at least?

**Comment by soranoba** [comment]
Ok.

In mustache, you can use innumerable key, but the number of atom on ErlangVM there is limit.
Therefore, there is no option to support the atom only.

But, it is great that people who use this library can choose their favorite type (string, atom and binary) as keys.

Please wait a little because corresponding to the weekend.

**Comment by soranoba** [comment]
Master has been updated ! (v0.3.0)

1.  Specify the type in key_type (See #4)
```erlang
# Default
1> mustache:render(<<"{{a}}">>, [{"a", "string"}]).
<<"string">>
2> mustache:render(<<"{{a}}">>, [{a, "atom"}], [{key_type, atom}]).
<<"atom">>
3> mustache:render(<<"{{a}}">>, [{<<"a">>, "binary"}], [{key_type, binary}]).
<<"binary">>
```

2.  It is not exist conversion for key when key_type is the binary
https://github.com/soranoba/mustache/blob/v0.3.0/src/mustache.erl#L314

3.  Take over the key_type when you use the Lamda expressions.
https://github.com/soranoba/mustache/blob/v0.3.0/src/mustache.erl#L138

**Comment by soranoba** [comment]
4. All key in assoc list or maps must be same type.
https://github.com/soranoba/mustache/blob/v0.3.0/src/mustache.erl#L71

```erlang
1> #{"hoge" => "hoge", "fugo" => "fugo"}. % Ok
2> #{"hoge" => "hoge", atom => "atom"} % Bad
```
